model:
  arch: blip2_t5_instruct_lora
  model_type: flant5xl
  load_pretrained: True #pretrain from scratch
  freeze_vit: True
  llm_lora_r: 1
  llm_lora_apply: all
  
datasets:
  scienceqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    train_samples_portion: all
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 224
      eval:
        name: "blip_image_eval"
        image_size: 224
    text_processor:
      train:
        name: "instruct_blip_question"
      eval:
        name: "instruct_blip_question"

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /mnt/d/BLIP/InstructBLIP_PEFT/input/scienceqa/scienceqa_train.json
        val:
          storage: /mnt/d/BLIP/InstructBLIP_PEFT/input/scienceqa/scienceqa_val.json
        test:
          storage: /mnt/d/BLIP/InstructBLIP_PEFT/input/scienceqa/scienceqa_test.json
      images:
        storage: /mnt/d/BLIP/InstructBLIP_PEFT/input
        train:
          storage: /mnt/d/BLIP/InstructBLIP_PEFT/input
        val:
          storage: /mnt/d/BLIP/InstructBLIP_PEFT/input
        test:
          storage: /mnt/d/BLIP/InstructBLIP_PEFT/input

run:
  task: scienceqa
  # optimizer
  lr_sched: "linear_decay_lr"
  init_lr: 5e-4
  min_lr: 0
  warmup_lr: 5e-4
  warmup_steps: 0

  weight_decay: 0.05
  max_epoch: 10
  batch_size_train: 1
  accum_grad_iters: 2
  batch_size_eval: 1
  num_workers: 1

  # inference-specific
  inference_method: "rank"

  seed: 42
  output_dir: "/mnt/d/BLIP/InstructBLIP_PEFT/output/results/scienceqa/scienceqa_1"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: ["train"]
  valid_splits: ["val"]
  test_splits: ["test"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True